name: afad_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
# flutter 3.10.4
# dart 3.0.3
environment:
  sdk: "3.0.6"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.5"
  flutter_bluetooth_serial: "0.4.0"
  location: "5.0.1"
  awesome_snackbar_content: ^0.1.3
  permission_handler: ^10.4.3
  google_sign_in: "6.1.4"
  flutter_riverpod: "2.3.6"
  riverpod_annotation: "2.1.1"
  easy_localization: ^3.0.1
  firebase_core_platform_interface: "4.8.0"
  firebase_core: "2.14.0"
  cloud_firestore: "4.4.3"
  firebase_auth: "4.6.2"
  cloud_functions: "4.0.11"
  firebase_analytics: "10.1.4"
  firebase_crashlytics: "3.0.15"
  firebase_dynamic_links: "5.0.15"
  firebase_storage: "11.0.14"
  firebase_messaging: "14.2.5"
  firebase_remote_config: "3.0.13"
  freezed_annotation: "2.2.0"
  json_annotation: "4.8.1"
  logger: ^2.0.1
  loading:
    git:
      url: https://github.com/adnanjpg/loading.git
  life_saver_extensions:
    git:
      url: https://github.com/adnanjpg/life_saver_extensions.git
  google_fonts: "5.1.0"
  go_router: ^6.0.1
  uuid: ^3.0.7
  device_info_plus: ^9.0.3
  app_tracking_transparency: ^2.0.4
  # country_picker: ^2.0.19
  country_picker:
    # this package has a problem as it is filling the ui
    # and not respecting the constraints.
    # i've forked it and fixed it and submitted a PR.
    # until it is merged, use this forked version.
    # https://github.com/Daniel-Ioannou/flutter_country_picker/pull/108
    git:
      url: https://github.com/adnanjpg/flutter_country_picker.git
      ref: ui-filling-fix
  connectivity_plus: ^4.0.2
  image_cropper: ^5.0.0
  image_picker: ^1.0.2
  font_awesome_flutter: "10.4.0"
  google_maps_flutter: ^2.4.0
  google_maps_flutter_web: ^0.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "2.0.2"
  freezed: "2.3.5"
  build_runner:
  json_serializable: "6.7.0"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/images/intro/
    - assets/images/home/
    - assets/images/home/quizzes/
    - assets/fonts/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
